### PR TITLE
Formal verification of the entire interrupt virtualization pipeline

### PR DESCRIPTION
**Pull request by francois141**
This commit extends model checking to the entire interrupt virtualization pipeline. It builds-up on the previous model checking infrastructure.

The famous branch that got force-pushed :)

### CODE REVIEW

**Comment by CharlyCst** [comment]
@francois141 I rebased the PR as it was targeting an old branch. You can double check that everything looks OK.

Just one question before merging this, where does the `step_interrupt_only` function? It seems you created it from `step`, so you added it to the custom Sail model?

Otherwise looks pretty cool, so now we can check interrupts end-to-end :)

**Comment by francois141** [comment]
Indeed. The step function is something like

```C
if interrupt_ready() {
fire
} else {
fetch_decode_execute()
}
```

I replace with 

```C
if interrupt_ready() {
fire
} else {
 // Nothing 
}
```

**Comment by CharlyCst** [comment]
Where did you do the change? On the Sail model or directly on the Rust code? How can I reproduce it?

If it is on the Sail model, can you add it on the repo (https://github.com/epfl-dcsl/miralis-sail-riscv/tree/miralis) ?

**Comment by francois141** [comment]
@CharlyCst I pushed the modifications on the sail mode, done

**Pull request merged**
