### PR TITLE
Integrate Clippy (linter) in the CI/CD pipeline

### PR DESCRIPTION
**Pull request by francois141**

### CODE REVIEW

**Comment by francois141** [comment]
@CharlyCst This PR is a follow up of the previous one. Clippy seems to be a good extension to cargo fmt and cargo deny

**Comment by CharlyCst** [comment]
It seems that `cargo clippy` only checks the default crate of the workspace (which is the runner), so Miralis itself is not checked it seems.

The whole workspace can be checked with `cargo clippy --workspace --features userspace`. The `userspace` features is necessary to check Miralis for the host target (clippy is a bit lost when checking RISC-V assembly it seems). But there are quite a few more warnings to fix...
Let's keep that around here until we manage to fix most lints :)

**Comment by francois141** [comment]
Good catch! I was a bit surprised to get only warnings in that package. I should have doubled checked. Let me see what I can do for the risc-v assembly and fix the other lints

**Comment by francois141** [comment]
@CharlyCst Ready to review!

**Comment by CharlyCst** [comment]
I rebased the PR (there was a conflict with another one I merged this morning that I fixed), and disabled the deny warning in the justfile to make development easier (the warning are still disabled in the CI by the "RUSTFLAGS" environment variable).

Thanks for pushing the changes, that's super cool :)

**Pull request merged**
