### PR TITLE
Add U-boot test in the CI / CD pipeline

### PR DESCRIPTION
**Pull request by francois141**
U-Boot is a universal bootloader used to initialize system hardware and load the operating system. The test terminates execution just before transferring control to the OS. This approach focuses on verifying U-Boot’s functionality without requiring the full boot sequence.

### CODE REVIEW

**Comment by francois141** [comment]
@CharlyCst Code is ready! Let's first merge the other repo & then we can run this pipeline and it should be successful!

**Comment by CharlyCst** [comment]
I'll take a look at merging this once the artifacts are available from the other repo :)

**Comment by francois141** [comment]
Ready to review!

**Comment by francois141** [comment]
@CharlyCst Ready to review!

**Pull request merged**
